///Generic Dimensions
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM_2 = 16.0;
const TEXT_HEADING_1x = 24.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_MEDIUM_3 = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;
///Border Radius
const BORDER_RADIUS_SMALL = 10.0;
const BORDER_RADIUS_MEDIUM = 20.0;
const BORDER_RADIUS_LARGE = 30.0;
const BORDER_RADIUS_XL = 40.0;

///Font SIze
const FONT_REGULAR = 14.0;
const FONT_REGULAR_2X = 16.0;
const FONT_REGULAR_3X = 20.0;
const FONT_HEADING_1X = 24.0;
const FONT_HEADING_2X = 28.0;
const FONT_BIG = 32.0;


///App Specific
const BANNER_SECTION_HEIGHT = 200.0;
const BANNER_PLAY_BUTTON_SIZE = 56.0;
const MOVIE_LIST_HEIGHT = 286.0;
const SHOW_CASES_HEIGHT = 240.0;
const MOVIE_LIST_ITEM_WIDTH = 180.0;
const BEST_ACTORS_HEIGHT = 200.0;
const SHOWTIME_SECTION_HEIGHT = 180.0;
const MOVIEW_DETAILS_SCREEN_SLIVER_APP_BAR_HEIGHT = 300.0;
const MOVIE_DETAILS_RATING_TEXT_SIZE = 56.0;
const double TITLE_FONT_SIZE = 24.0;
const double APPBAR_TITLE_FONT_SIZE = 22.0;
const double APPBAR_TEXT_BUTTON_FONT_SIZE = 20.0;
const double LARGE_FONT_SIZE = 18.0;
const double NORMAL_FONT_SIZE_2X = 16.0;
const double NORMAL_FONT_SIZE = 12.0;
const double SMALL_FONT_SIZE_14 = 14.0;
const double SMALL_FONT_SIZE_10 = 10.0;